from LinkedList import LinkedList
lista = LinkedList()
lista.AddNode(5)
lista.AddNode(5)
lista.AddNode(5)
lista.AddNode(5)
print(lista)
print(lista.PTR)
lista.DeleteNode(5)
print(lista)
print(lista.PTR)
